/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.translator

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.translator.handlers.HandlerInput
import com.translator.handlers.HandlerOutput

class App : RequestHandler<HandlerInput, HandlerOutput> {

    private val translator: PirateTranslator = DefaultPirateTranslator()

    override fun handleRequest(input: HandlerInput?, context: Context?): HandlerOutput {
        input?.let {
            return HandlerOutput(it.message, translator.translate(it.message))
        }
        return HandlerOutput("", "");
    }
}

